/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardRoadmapRouteImport } from './routes/dashboard.roadmap'
import { Route as DashboardResumeRouteImport } from './routes/dashboard.resume'
import { Route as DashboardMockInterviewRouteImport } from './routes/dashboard.mock-interview'
import { Route as DashboardDsaRouteImport } from './routes/dashboard.dsa'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRoadmapRoute = DashboardRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardResumeRoute = DashboardResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMockInterviewRoute = DashboardMockInterviewRouteImport.update({
  id: '/mock-interview',
  path: '/mock-interview',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDsaRoute = DashboardDsaRouteImport.update({
  id: '/dsa',
  path: '/dsa',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/dsa': typeof DashboardDsaRoute
  '/dashboard/mock-interview': typeof DashboardMockInterviewRoute
  '/dashboard/resume': typeof DashboardResumeRoute
  '/dashboard/roadmap': typeof DashboardRoadmapRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/dsa': typeof DashboardDsaRoute
  '/dashboard/mock-interview': typeof DashboardMockInterviewRoute
  '/dashboard/resume': typeof DashboardResumeRoute
  '/dashboard/roadmap': typeof DashboardRoadmapRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/dsa': typeof DashboardDsaRoute
  '/dashboard/mock-interview': typeof DashboardMockInterviewRoute
  '/dashboard/resume': typeof DashboardResumeRoute
  '/dashboard/roadmap': typeof DashboardRoadmapRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/dsa'
    | '/dashboard/mock-interview'
    | '/dashboard/resume'
    | '/dashboard/roadmap'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/dsa'
    | '/dashboard/mock-interview'
    | '/dashboard/resume'
    | '/dashboard/roadmap'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/dsa'
    | '/dashboard/mock-interview'
    | '/dashboard/resume'
    | '/dashboard/roadmap'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/roadmap': {
      id: '/dashboard/roadmap'
      path: '/roadmap'
      fullPath: '/dashboard/roadmap'
      preLoaderRoute: typeof DashboardRoadmapRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/resume': {
      id: '/dashboard/resume'
      path: '/resume'
      fullPath: '/dashboard/resume'
      preLoaderRoute: typeof DashboardResumeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/mock-interview': {
      id: '/dashboard/mock-interview'
      path: '/mock-interview'
      fullPath: '/dashboard/mock-interview'
      preLoaderRoute: typeof DashboardMockInterviewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/dsa': {
      id: '/dashboard/dsa'
      path: '/dsa'
      fullPath: '/dashboard/dsa'
      preLoaderRoute: typeof DashboardDsaRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardDsaRoute: typeof DashboardDsaRoute
  DashboardMockInterviewRoute: typeof DashboardMockInterviewRoute
  DashboardResumeRoute: typeof DashboardResumeRoute
  DashboardRoadmapRoute: typeof DashboardRoadmapRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDsaRoute: DashboardDsaRoute,
  DashboardMockInterviewRoute: DashboardMockInterviewRoute,
  DashboardResumeRoute: DashboardResumeRoute,
  DashboardRoadmapRoute: DashboardRoadmapRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
